### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jeanfboueri** [NDEats/NDEats-Back-End#38]
- [x] The orders currently are shown from top to bottom, we want them to be shown from bottom to top (Reverse Orders) - **frontend**
- [x] Pickup order (take order), the request is in the README.md - **frontend**
- [x] Update README.md fully - **backend**
- [x] Email functionality - **backend**
- [x] My orders page - **front end**
- [x] Deploy - **frontend and backend**
- [x] Filtering orders - **backend**
- [x] Make sure user doesn't pick up their own order - **backend**
- [x] Add an "About Us" page in top right or bottom right or smtg - **frontend**
- [x] Fix the my orders page (broken w/ the venmo update?) - **frontend**
- [x] Return user's orders should also return the orders you agreed to pick up - **backend**
- [x] Allow user to input the pickup location (or have a dropdown menu that includes Chicfila, not just Duncan) - **frontend**
- [x] Write instructions in the final report
- [x] Use the "dropoff" api --> important for removing order from my orders page

**Comment by bgoodwine** [comment]
<img width="1032" alt="Screenshot 2022-12-09 at 11 08 21 AM" src="https://user-images.githubusercontent.com/65368903/206744365-aac59002-0d88-4acd-b056-f79b3e45e46a.png">
